### ISSUE TITLE
Error when try to install this plugin

### ISSUE THREAD

**Issue by shadowinlife** [AnnaGerber/kibana_dropdown#1]
How can I install this plugin to my kibana-5.0.1? I have tried to build a zip file mysefl as below steps

npm version 4.0.2
node.js version v0.10.46
npm install
npm run build
with error info here:

```
var buildId = `${plugin.id}-${plugin.version`;
                
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/kibana/src/plugins/kibana_dropdown/node_modules/@elastic/plugin-helpers/lib/command.js:8:14)
    at Object.<anonymous> (/kibana/src/plugins/kibana_dropdown/node_modules/@elastic/plugin-helpers/bin/plugin-helpers-build.js:3:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by v01t** [comment]
Same for me but with different error:

`{
 "type":"log",
 "@timestamp":"2016-12-03T15:48:59Z",
 "tags":["fatal"],
 "pid":17782,
 "level":"fatal",
 "message":"Optimizations failure.\n\n    ERROR in /usr/share/kibana/plugins/dropdown/public/dropdownpicker.less\n    Module build failed: Error: Loader /usr/share/kibana/plugins/dropdown/node_modules/css/index.js didn't return a function\n        at DependenciesBlock.loadPitch (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:215:20)\n        at DependenciesBlock.doBuild (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)\n        at DependenciesBlock.build (/usr/share/kibana/node_modules/webpack/lib/NormalModule.js:84:14)\n        at Compilation.buildModule (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:126:9)\n        at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:398:8)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:58:13\n        at NormalModuleFactory.applyPluginsAsyncWaterfall (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:75:69)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:38:11)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:121:6)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:98:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:726:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:52:16\n        at async.forEachOf.async.eachOf (/usr/share/kibana/node_modules/async/lib/async.js:236:30)\n        at _parallel (/usr/share/kibana/node_modules/async/lib/async.js:717:9)\n        at Object.async.parallel (/usr/share/kibana/node_modules/async/lib/async.js:731:9)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:75:10\n     @ /usr/share/kibana/plugins/dropdown/public/dropdownpicker.js 12:2-56\n","error":{"message":"Optimizations failure.\n\n    \u001b[1m\u001b[31mERROR in /usr/share/kibana/plugins/dropdown/public/dropdownpicker.less\n    Module build failed: Error: Loader /usr/share/kibana/plugins/dropdown/node_modules/css/index.js didn't return a function\n        at DependenciesBlock.loadPitch (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:215:20)\n        at DependenciesBlock.doBuild (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)\n        at DependenciesBlock.build (/usr/share/kibana/node_modules/webpack/lib/NormalModule.js:84:14)\n        at Compilation.buildModule (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:126:9)\n        at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:398:8)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:58:13\n        at NormalModuleFactory.applyPluginsAsyncWaterfall (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:75:69)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:38:11)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:121:6)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:98:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:726:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:52:16\n        at async.forEachOf.async.eachOf (/usr/share/kibana/node_modules/async/lib/async.js:236:30)\n        at _parallel (/usr/share/kibana/node_modules/async/lib/async.js:717:9)\n        at Object.async.parallel (/usr/share/kibana/node_modules/async/lib/async.js:731:9)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:75:10\n     @ /usr/share/kibana/plugins/dropdown/public/dropdownpicker.js 12:2-56\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n\n    \u001b[1m\u001b[31mERROR in /usr/share/kibana/plugins/dropdown/public/dropdownpicker.less\n    Module build failed: Error: Loader /usr/share/kibana/plugins/dropdown/node_modules/css/index.js didn't return a function\n        at DependenciesBlock.loadPitch (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:215:20)\n        at DependenciesBlock.doBuild (/usr/share/kibana/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)\n        at DependenciesBlock.build (/usr/share/kibana/node_modules/webpack/lib/NormalModule.js:84:14)\n        at Compilation.buildModule (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:126:9)\n        at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:398:8)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:58:13\n        at NormalModuleFactory.applyPluginsAsyncWaterfall (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:75:69)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:38:11)\n        at onDoneResolving (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:121:6)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:98:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:726:13\n        at /usr/share/kibana/node_modules/async/lib/async.js:52:16\n        at async.forEachOf.async.eachOf (/usr/share/kibana/node_modules/async/lib/async.js:236:30)\n        at _parallel (/usr/share/kibana/node_modules/async/lib/async.js:717:9)\n        at Object.async.parallel (/usr/share/kibana/node_modules/async/lib/async.js:731:9)\n        at /usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:75:10\n     @ /usr/share/kibana/plugins/dropdown/public/dropdownpicker.js 12:2-56\u001b[39m\u001b[22m\n\n    at Object.exports.create (/usr/share/kibana/node_modules/boom/lib/index.js:21:17)\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:228:32)\n    at /usr/share/kibana/src/optimize/fs_optimizer.js:53:29\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)\n    at /usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12\n    at Compiler.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)\n    at Compiler.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:577:13)\n    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)\n    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)\n    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)"}}`

**Comment by ghost** [comment]
I have this error when trying to install from url of from zip archive via the bin/kibana-plugin install command:

from git url:
```
root@machine:/usr/share/kibana#` bin/kibana-plugin install https://github.com/AnnaGerber/kibana_dropdown.git
Attempting to transfer from https://github.com/AnnaGerber/kibana_dropdown.git
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:179:14
    at /usr/share/kibana/node_modules/yauzl/index.js:539:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

from local zip archive:
```
root@machine:/usr/share/kibana# bin/kibana-plugin install file:/tmp/kibana_dropdown-master.zip  -d /usr/share/kibana/plugins/kibana_dropdown/
Attempting to transfer from file:/tmp/kibana_dropdown-master.zip
Transferring 344260 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```
